const enc=new TextEncoder(),cookieName='__Host-practice';
const attempts=new Map();
const htmlEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY'};
function page(message='',status=200){return new Response(`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Вход — ВерПрактикум</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f5fa;color:#20263b;font:16px/1.6 system-ui;min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:100%;max-width:440px;background:white;border:1px solid #e3e7f1;border-radius:20px;padding:36px;box-shadow:0 16px 60px #20263b0b}.brand{color:#6151da;font-weight:750;letter-spacing:.02em}h1{font-size:30px;line-height:1.2;margin:24px 0 12px}p{color:#65718a}label{display:block;font-weight:600;margin-top:18px}input,button{width:100%;font:inherit;border-radius:9px;padding:12px 14px}input{border:1px solid #cdd3e1;margin-top:6px}input:focus{outline:3px solid #d8d1ff;border-color:#6151da}button{border:0;background:#6151da;color:white;font-weight:650;margin-top:24px;cursor:pointer}.error{color:#aa2747}.note{font-size:14px;margin-bottom:0}body{background:radial-gradient(ellipse at top left,#e2ecff,transparent 60%),#f5f8fc;color:#19283e;font-size:17px;line-height:1.75}.card{max-width:480px;border-radius:24px;padding:42px;border-color:#d6e1f1;box-shadow:0 24px 70px #203f6610}.brand{color:#315be8;font-size:16px}h1{font-size:34px;letter-spacing:-1px;margin-top:28px}p{color:#52657d}label{font-size:16px;color:#304762;margin-top:22px}input{min-height:54px;background:#f8faff;border-color:#c7d6eb;border-radius:12px;padding:14px 16px}input:focus{outline:3px solid #a5c1ff;border-color:#315be8}button{background:#315be8;min-height:54px;border-radius:12px;font-size:17px;box-shadow:0 6px 16px #315be824;transition:background .15s,transform .15s}button:hover{background:#244ac8;transform:translateY(-1px)}button:focus-visible{outline:3px solid #315be8;outline-offset:4px}.note{font-size:15px;line-height:1.8}.error{background:#fff1f3;border:1px solid #f1c7d0;padding:12px 16px;border-radius:10px;color:#a12a44}@media(max-width:500px){body{padding:18px}.card{padding:28px 24px}h1{font-size:29px}}@media(prefers-reduced-motion:reduce){button{transition:none}}
</style><main class="card"><div class="brand">›_ ВерПрактикум</div><h1>Вход в тренажёры</h1><p>SQL · BPMN · API · Python</p>${message?`<p role="alert" class="error">${htmlEscape(message)}</p>`:''}<form method="post" action="/auth/login"><label for="username">Общий логин</label><input id="username" name="username" autocomplete="username" maxlength="128" required autofocus><label for="password">Пароль</label><input id="password" name="password" type="password" autocomplete="current-password" maxlength="256" required><button>Войти</button></form><p class="note">Логин и пароль выдаёт владелец сайта. Прогресс сохраняется отдельно в вашем браузере.</p></main></html>`,{status,headers:{...headers,'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'"}})}
const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
function unb64(s){return Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0))}
async function digest(s){return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function same(a,b){const [x,y]=await Promise.all([digest(a),digest(b)]);let n=0;for(let i=0;i<x.length;i++)n|=x[i]^y[i];return n===0}
async function key(env){return crypto.subtle.importKey('raw',await digest(JSON.stringify([env.SESSION_SECRET,env.SHARED_LOGIN,env.SHARED_PASSWORD])),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
async function token(env){const payload=b64(enc.encode(JSON.stringify({exp:Date.now()+12*60*60*1000,nonce:crypto.randomUUID()})));const sig=await crypto.subtle.sign('HMAC',await key(env),enc.encode(payload));return payload+'.'+b64(sig)}
async function authorized(request,env){try{const value=(request.headers.get('Cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!value||value.length>1024)return false;const parts=value.split('.');if(parts.length!==2)return false;const [p,s]=parts;if(!await crypto.subtle.verify('HMAC',await key(env),unb64(s),enc.encode(p)))return false;const data=JSON.parse(new TextDecoder().decode(unb64(p)));return Number.isFinite(data.exp)&&data.exp>Date.now()&&data.exp<=Date.now()+12*60*60*1000}catch{return false}}
function redirect(path,cookie){return new Response(null,{status:303,headers:{...headers,Location:path,...cookie?{'Set-Cookie':cookie}:{}}})}
function configured(env){return typeof env.SHARED_LOGIN==='string'&&env.SHARED_LOGIN.length>0&&typeof env.SHARED_PASSWORD==='string'&&env.SHARED_PASSWORD.length>=12&&typeof env.SESSION_SECRET==='string'&&env.SESSION_SECRET.length>=32}
export function createApp(assets){return {async fetch(request,env){
 const url=new URL(request.url),path=url.pathname;
 if(request.method==='POST'&&(path==='/auth/login'||path==='/auth/logout')){
  if(request.headers.get('Origin')!==url.origin)return new Response('Запрос отклонён.',{status:403,headers});
  if(path==='/auth/logout')return redirect('/login/',`${cookieName}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`);
  if(!configured(env))return page('Владелец ещё не настроил общий вход.',503);
  if(!request.headers.get('Content-Type')?.startsWith('application/x-www-form-urlencoded'))return page('Неверный формат запроса.',415);
  if(Number(request.headers.get('Content-Length'))>4096)return page('Слишком большой запрос.',413);
  const reader=request.body?.getReader();let size=0,chunks=[];if(reader){while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4096){await reader.cancel();return page('Слишком большой запрос.',413)}chunks.push(value)}}
  const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const form=new URLSearchParams(new TextDecoder().decode(bytes));
  // Best-effort per-isolate abuse limit; no claim of globally distributed limiting.
  const ip=request.headers.get('CF-Connecting-IP')||'unknown',now=Date.now();for(const [k,v] of attempts)if(v.until<now)attempts.delete(k);if(attempts.size>5000)attempts.clear();const record=attempts.get(ip)||{count:0,until:now+60000};if(record.count>=10)return page('Слишком много попыток. Подождите минуту.',429);record.count++;attempts.set(ip,record);
  const username=form.get('username')||'',password=form.get('password')||'';const validName=await same(username,env.SHARED_LOGIN),validPass=await same(password,env.SHARED_PASSWORD);if(!validName||!validPass)return page('Неверный логин или пароль.',401);attempts.delete(ip);return redirect('/',`${cookieName}=${await token(env)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`);
 }
 if(path==='/login/'||path==='/login')return page();
 if(!configured(env))return page('Общий вход ещё не настроен. Обратитесь к владельцу.',503);
 if(!await authorized(request,env)){if(request.headers.get('Sec-Fetch-Dest')==='document'||request.headers.get('Accept')?.includes('text/html')||path==='/'||path.endsWith('/'))return redirect('/login/');return new Response('Необходим вход.',{status:401,headers})}
 if(path==='/auth/account'){return new Response(`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Аккаунт — ВерПрактикум</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/comfort.css?v=1"><main style="max-width:540px;margin:10vh auto;padding:24px"><h1>Общий доступ</h1><p>Вы вошли в ВерПрактикум. Прогресс хранится в вашем браузере.</p><p><a href="/">SQL</a> · <a href="/bpmn/">BPMN</a> · <a href="/api/">API</a> · <a href="/python/">Python</a></p><form method="post" action="/auth/logout"><button class="primary">Выйти</button></form></main></html>`,{headers:{...headers,'Content-Type':'text/html; charset=utf-8'}})}
 if(!['GET','HEAD'].includes(request.method))return new Response('Метод не поддерживается.',{status:405,headers});
 const name=path.endsWith('/')?path+'index.html':path;const asset=Object.prototype.hasOwnProperty.call(assets,name)?assets[name]:null;if(!asset)return new Response('Страница не найдена.',{status:404,headers});const data=Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0));return new Response(request.method==='HEAD'?null:data,{headers:{...headers,'Content-Type':asset.type}});
}}}
