import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createApp} from '../server/auth.mjs';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const app=createApp({'/index.html':{data:btoa('protected'),type:'text/html'},'/data.js':{data:btoa('secret lesson'),type:'text/javascript'},'/api/sw.js':{data:btoa('worker'),type:'text/javascript'}});
const env={SHARED_LOGIN:'student',SHARED_PASSWORD:'test-only-password-123',SESSION_SECRET:'test-only-signing-key-at-least-32-characters'};
const call=(path,options={},config=env)=>app.fetch(new Request('https://practice.test'+path,options),config);
const post=(username,password,extra={})=>({method:'POST',headers:{Origin:'https://practice.test','Content-Type':'application/x-www-form-urlencoded',...extra},body:new URLSearchParams({username,password})});
assert.equal((await call('/')).status,303);
assert.equal((await call('/data.js')).status,401);
assert.equal((await call('/api/sw.js')).status,401);
assert.equal((await call('/login/')).status,200);
assert.equal((await call('/',{},{})).status,503);
assert.equal((await call('/auth/login',post('student','wrong'))).status,401);
assert.equal((await call('/auth/login',post('student',env.SHARED_PASSWORD,{Origin:'https://evil.test'}))).status,403);
let response=await call('/auth/login',post('student',env.SHARED_PASSWORD));assert.equal(response.status,303);const cookie=response.headers.get('set-cookie');for(const flag of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.ok(cookie.includes(flag));const session=cookie.split(';')[0];
assert.equal(await (await call('/',{headers:{Cookie:session}})).text(),'protected');
assert.equal((await call('/data.js',{headers:{Cookie:session}})).status,200);
assert.equal((await call('/data.js',{headers:{Cookie:session+'X'}})).status,401);
assert.equal((await call('/data.js',{headers:{Cookie:session}},{...env,SHARED_PASSWORD:'new-test-password-123'})).status,401);
response=await call('/auth/logout',{method:'POST',headers:{Origin:'https://practice.test',Cookie:session}});assert.equal(response.status,303);assert.ok(response.headers.get('set-cookie').includes('Max-Age=0'));
for(let i=0;i<10;i++)await call('/auth/login',post('student','wrong',{'CF-Connecting-IP':'test-limit'}));assert.equal((await call('/auth/login',post('student','wrong',{'CF-Connecting-IP':'test-limit'}))).status,429);
assert.equal((await call('/auth/login',post('x','x'.repeat(5000)))).status,413);
console.log('PASS: protected pages/assets, no-credentials fail closed, login, signed cookie, tampering, rotation, CSRF, logout, attempt and body limits.');
